name: Create Orphan Branch, Add Images and Comment
description: "render diff"
inputs:
  config-path:
    description: "Path to the config file"
    default: "archlens.json"
  render-diff:
    description: "Should it render diff"
    default: "true"
  BRANCH_NAME: 
    description: "name for the new orphan branch"
    required: true

runs:
  using: 'composite'
  steps:

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - uses: actions/checkout@v3
    - name: Checkout code
      run: |
        git checkout --orphan ${{ inputs.BRANCH_NAME }}
        ls -la
      shell: bash

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install archlens-preview
      shell: bash

    - name: Run Architectural Lens
      id: run_archlens
      run: |
        ls -la
        if [ "${{inputs.render-diff}}" == "true" ]
        then
          OUTPUT=$(MT_DEBUG="true" archlens render-diff --config-path ${{ inputs.config-path }})
          echo "$OUTPUT"
          # Extract the list of changed views
          CHANGED_VIEWS=$(echo "$OUTPUT" | grep -oP 'ARCHLENS_CHANGED_VIEWS=\K.*' || echo "")
          if [ -z "$CHANGED_VIEWS" ]; then
            echo "HAS_CHANGES=false" >> $GITHUB_OUTPUT
            echo "No architectural changes detected."
            exit 0
          else
            echo "HAS_CHANGES=true" >> $GITHUB_OUTPUT
            echo "CHANGED_VIEWS=$CHANGED_VIEWS" >> $GITHUB_OUTPUT
          fi
        else
          MT_DEBUG="true" archlens render --config-path ${{ inputs.config-path }}
          echo "HAS_CHANGES=true" >> $GITHUB_OUTPUT
          # For non-diff mode, include all views
          CHANGED_VIEWS=""
        fi

        # get the pull request ID from the ref
        IN=${{github.ref}}
        arrIN=(${IN//\// })
        PULL_REQUEST_ID=${arrIN[2]}

        # read the saveLocation from the json config
        DIAGRAMS_FOLDER=$(jq -r '.saveLocation' ${{ inputs.config-path }})

        # save a stripped version as well
        STRIPPED_FOLDER_NAME=${DIAGRAMS_FOLDER#./} #remove leading "./"
        STRIPPED_FOLDER_NAME=${STRIPPED_FOLDER_NAME%/}  #remove trailing "/"

        # create a unique folder name (concat pull request ID)
        UNIQUE_NAME=$STRIPPED_FOLDER_NAME-$PULL_REQUEST_ID

        # rename the savelocation to our unique name
        echo mv $STRIPPED_FOLDER_NAME $UNIQUE_NAME
        mv $STRIPPED_FOLDER_NAME $UNIQUE_NAME

        # prefix all the png files with the workflow run_number
        cd $UNIQUE_NAME
        for f in * ; do mv -- "$f" "${{ github.run_number }}-$f" ; done

        git reset
        git config --global user.name "ArchLens bot"
        git config --global user.email "archlens@users.noreply.github.com"
        git add -f .
        cd ..
        git clean -d -f .
        git commit -m "Add diagrams"
        git config pull.rebase false

        # pull from remote before push (fail silently, if no remote exists its fine)
        git pull origin ${{ inputs.BRANCH_NAME }} --allow-unrelated-histories || true
        git push origin ${{ inputs.BRANCH_NAME }}

        cd $UNIQUE_NAME
        resultStr=""

        # Convert changed views to array for filtering
        IFS=',' read -ra CHANGED_VIEWS_ARRAY <<< "$CHANGED_VIEWS"

        # for each file, we append the markdown for showing the png to a string
        # only include files for views that have changes
        for file in *; do
          if (( ${{ github.run_number }} == "${file%%-*}" )); then
            # For render-diff mode, filter by changed views
            if [ "${{inputs.render-diff}}" == "true" ] && [ -n "$CHANGED_VIEWS" ]; then
              # Extract view name from filename: {run_number}-{project_name}-diff-{view_name}.png
              # Remove run number prefix and .png suffix, then extract view name after "-diff-"
              filename_without_prefix="${file#*-}"  # Remove run number
              view_name="${filename_without_prefix##*-diff-}"  # Get everything after "-diff-"
              view_name="${view_name%.png}"  # Remove .png extension

              # Check if this view is in the changed views list
              for changed_view in "${CHANGED_VIEWS_ARRAY[@]}"; do
                if [ "$view_name" == "$changed_view" ]; then
                  resultStr+="![diff](https://raw.githubusercontent.com/${{github.repository}}/${{ inputs.BRANCH_NAME }}/$UNIQUE_NAME/$file)"$'\n'
                  break
                fi
              done
            else
              # For non-diff mode, include all files
              resultStr+="![diff](https://raw.githubusercontent.com/${{github.repository}}/${{ inputs.BRANCH_NAME }}/$UNIQUE_NAME/$file)"$'\n'
            fi
          fi
        done

        # output the full markdown
        echo "MARKDOWN<<EOF" >> $GITHUB_OUTPUT
        echo "$resultStr" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      shell: bash

    - uses: mshick/add-pr-comment@v2
      if: steps.run_archlens.outputs.HAS_CHANGES == 'true'
      with:
        message: |
          Module view diffs:
          ${{ steps.run_archlens.outputs.MARKDOWN }}

    - uses: mshick/add-pr-comment@v2
      if: steps.run_archlens.outputs.HAS_CHANGES == 'false'
      with:
        message: |
          No architecturally relevant changes to the existing views (ArchLens)

