name: Create Orphan Branch, Add Images and Comment
description: "render diff"
inputs:
  config-path:
    description: "Path to the config file"
    default: "archlens.json"
  render-diff:
    description: "Should it render diff"
    default: "true"
  BRANCH_NAME: 
    description: "name for the new orphan branch"
    required: true

runs:
  using: 'composite'
  steps:

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - uses: actions/checkout@v3
    - name: Checkout code
      run: |
        git checkout --orphan ${{ inputs.BRANCH_NAME }}
        ls -la
      shell: bash

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install archlens-preview
      shell: bash

    - name: Run Architectural Lens
      run: |
        ls -la
        if [ "${{inputs.render-diff}}" == "true" ] 
        then
          MT_DEBUG="true" archlens render-diff --config-path ${{ inputs.config-path }}
        else
          MT_DEBUG="true" archlens render --config-path ${{ inputs.config-path }}
        fi


        IN=${{github.ref}} 
        arrIN=(${IN//\// })
        PULL_REQUEST_ID=${arrIN[2]}


        
        DIAGRAMS_FOLDER=$(jq -r '.saveLocation' ${{ inputs.config-path }})

        echo $DIAGRAMS_FOLDER

        STRIPPED_FOLDER_NAME=${DIAGRAMS_FOLDER#./} #remove leading "./"
        STRIPPED_FOLDER_NAME=${STRIPPED_FOLDER_NAME%/}  #remove trailing "/"

        echo $STRIPPED_FOLDER_NAME
        UNIQUE_NAME=$STRIPPED_FOLDER_NAME-$PULL_REQUEST_ID
        
        mv $STRIPPED_FOLDER_NAME $UNIQUE_NAME

        cd $UNIQUE_NAME
        ls -la
        for f in * ; do mv -- "$f" "${{ github.run_number }}$f" ; done
        cd ..
      

      shell: bash

    - name: Commit and push images
      id: commit_images
      run: |
        git config --global user.name "ArchLens bot"
        git config --global user.email "archlens@users.noreply.github.com"
        git reset
        git add -f $UNIQUE_NAME/*
        git commit -m "Add diagrams"
        git push origin ${{ inputs.BRANCH_NAME }}

        files=()

        for file in $UNIQUE_NAME/*; do
          files+=("$file")
        done

        resultStr=""

        for file in "${files[@]}"; do
          resultStr+="![diff](https://raw.githubusercontent.com/${{github.repository}}/${{ inputs.BRANCH_NAME }}/$file)" 
        done

        echo "MARKDOWN=$resultStr" >> $GITHUB_OUTPUT

      shell: bash

    - uses: mshick/add-pr-comment@v2
      with:
        message: |
          Module view diffs:
          ${{ steps.commit_images.outputs.MARKDOWN }}
          
          
          