name: Create Orphan Branch, Add Images and Comment
description: "render diff"
inputs:
  config-path:
    description: "Path to the config file"
    default: "archlens.json"
  render-diff:
    description: "Should it render diff"
    default: "true"
  BRANCH_NAME: 
    description: "name for the new orphan branch"
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - name: Checkout code
      run: |
        git checkout --orphan ${{ inputs.BRANCH_NAME }}-${{github.run_id}}
        ls -la
      shell: bash

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e git+https://github.com/archlens/ArchLens@hotfix/use-public-plantuml-server#egg=architectural-lens
      shell: bash

    - name: Run Architectural Lens
      run: |
        ls -la
        if [ "${{inputs.render-diff}}" == "true" ] 
        then
          MT_DEBUG="true" archlens render-diff --config-path ${{ inputs.config-path }}
        else
          MT_DEBUG="true" archlens render --config-path ${{ inputs.config-path }}
        fi
        cd diagrams && ls -la && cd ..
      shell: bash

    # - name: Add images to diagrams/ directory
    #   run: |
    #     mkdir diagrams
    #     cp path_to_your_images/* diagrams/
    #   shell: bash

    - name: Commit and push images
      id: commit_images
      run: |
        git config --global user.name "ArchLens bot"
        git config --global user.email "archlens@users.noreply.github.com"
        git reset
        git add diagrams/*
        git commit -m "Add diagrams"
        git push origin ${{ inputs.BRANCH_NAME }}-${{github.run_id}}

        # Initialize an empty array
        files=()

        # Loop through all files in the specified folder and add them to the array
        for file in ./*.png; do
          files+=("$file")
        done

        # Append the length of the files list to GITHUB_OUTPUT
        echo "FILES_LENGTH=${#files[@]}" >> $GITHUB_OUTPUT

        # Join the array elements with a delimiter (e.g., newline) and append to GITHUB_OUTPUT
        for file in "${files[@]}"; do
          echo "$file" >> $GITHUB_OUTPUT
        done

      shell: bash

    # - name: Comment on PR with link to new branch
    #   run: |
    #     curl \
    #       -X POST \
    #       -H "Authorization: token ${{ inputs.GITHUB_TOKEN }}" \
    #       -H "Accept: application/vnd.github.v3+json" \
    #       https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments \
    #       -d "{\"body\":\"Done. The new orphan branch with diagrams can be found here.\"}"
    #   shell: bash
    - uses: mshick/add-pr-comment@v2
      with:
        message: |
          Here are the generated diagrams for this PR: \n
          ${{ steps.commit_images.outputs.FILES_LENGTH }}
          ${{ steps.commit_images.outputs. }}
          
          https://raw.githubusercontent.com/${{github.repository}}/${{ inputs.BRANCH_NAME }}-${{ github.run_id }}/diagrams/
          