name: Create Orphan Branch, Add Images and Comment
description: "render diff"
inputs:
  config-path:
    description: "Path to the config file"
    default: "archlens.json"
  render-diff:
    description: "Should it render diff"
    default: "true"
  BRANCH_NAME: 
    description: "name for the new orphan branch"
    required: true

runs:
  using: 'composite'
  steps:

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - uses: actions/checkout@v3
    - name: Checkout code
      run: |
        git checkout --orphan ${{ inputs.BRANCH_NAME }}
        ls -la
      shell: bash

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install archlens-preview
      shell: bash

    - name: Run Architectural Lens
      id: run_archlens
      run: |
        ls -la
        if [ "${{inputs.render-diff}}" == "true" ] 
        then
          MT_DEBUG="true" archlens render-diff --config-path ${{ inputs.config-path }}
        else
          MT_DEBUG="true" archlens render --config-path ${{ inputs.config-path }}
        fi

        # get the pull request ID from the ref
        IN=${{github.ref}} 
        arrIN=(${IN//\// })
        PULL_REQUEST_ID=${arrIN[2]}
        
        # read the saveLocation from the json config (e.g. "./archlens.json/")
        DIAGRAMS_FOLDER=$(jq -r '.saveLocation' ${{ inputs.config-path }})

        # save a stripped version as well
        STRIPPED_FOLDER_NAME=${DIAGRAMS_FOLDER#./} #remove leading "./"
        STRIPPED_FOLDER_NAME=${STRIPPED_FOLDER_NAME%/}  #remove trailing "/"

        # create a unique folder name (concat pull request ID)
        UNIQUE_NAME=$STRIPPED_FOLDER_NAME-$PULL_REQUEST_ID
        
        # rename the savelocation to our unique name
        mv $STRIPPED_FOLDER_NAME $UNIQUE_NAME

        # prefix all the png files with the workflow run_number
        cd $UNIQUE_NAME
        for f in * ; do mv -- "$f" "${{ github.run_number }}-$f" ; done

        git reset
        git config --global user.name "ArchLens bot"
        git config --global user.email "archlens@users.noreply.github.com"
        git add -f .
        cd ..
        git clean -d -f .
        git commit -m "Add diagrams"
        git config pull.rebase false

        # pull from remote before push (fail silently, if no remote exists its fine)
        git pull origin ${{ inputs.BRANCH_NAME }} --allow-unrelated-histories || true
        git push origin ${{ inputs.BRANCH_NAME }}

        cd $UNIQUE_NAME
        files=()

        for file in *; do
          files+=("$file")
        done

        resultStr=""

        # for each file, we append the markdown for showing the png to a string
        for file in "${files[@]}"; do
          if (( ${{ github.run_number }} == "${file%%-*}" ))
          then
            resultStr+="![diff](https://raw.githubusercontent.com/${{github.repository}}/${{ inputs.BRANCH_NAME }}/$UNIQUE_NAME/$file)" 
          fi
        done

        # output the full markdown
        echo "MARKDOWN=$resultStr" >> $GITHUB_OUTPUT
      shell: bash

    - uses: mshick/add-pr-comment@v2
      with:
        message: |
          Module view diffs:
          ${{ steps.run_archlens.outputs.MARKDOWN }}
          
          
          