name: Create Orphan Branch, Add Images and Comment
description: "render diff"
inputs:
  config-path:
    description: "Path to the config file"
    default: "archlens.json"
  render-diff:
    description: "Should it render diff"
    default: "true"
  BRANCH_NAME: 
    description: "name for the new orphan branch"
    required: true

runs:
  using: 'composite'
  steps:

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - uses: actions/checkout@v3
    - name: Checkout code
      run: |
        git checkout --orphan ${{ inputs.BRANCH_NAME }}-${{github.run_id}}
        ls -la
      shell: bash

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install archlens-preview
      shell: bash

    - name: Run Architectural Lens
      run: |
        ls -la
        if [ "${{inputs.render-diff}}" == "true" ] 
        then
          MT_DEBUG="true" archlens render-diff --config-path ${{ inputs.config-path }}
        else
          MT_DEBUG="true" archlens render --config-path ${{ inputs.config-path }}
        fi
        cd diagrams && ls -la && cd ..
      shell: bash

    - name: Commit and push images
      id: commit_images
      run: |
        git config --global user.name "ArchLens bot"
        git config --global user.email "archlens@users.noreply.github.com"
        git reset
        git add diagrams/*
        git commit -m "Add diagrams"
        git push origin ${{ inputs.BRANCH_NAME }}-${{github.run_id}}

        files=()

        for file in diagrams/*; do
          files+=("$file")
        done

        resultStr=""

        for file in "${files[@]}"; do
          resultStr+="![diff](https://raw.githubusercontent.com/${{github.repository}}/${{ inputs.BRANCH_NAME }}-${{ github.run_id }}/$file)" 
        done

        echo "MARKDOWN=$resultStr" >> $GITHUB_OUTPUT

      shell: bash

    - uses: mshick/add-pr-comment@v2
      with:
        message: |
          Module view diffs:
          ${{ steps.commit_images.outputs.MARKDOWN }}
          
          
          